# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roi_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_roiWidget(object):
    def setupUi(self, roiWidget):
        roiWidget.setObjectName(_fromUtf8("roiWidget"))
        roiWidget.resize(846, 235)
        self.groupBox = QtGui.QGroupBox(roiWidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 461, 231))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setSpacing(2)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_34.addWidget(self.label)
        self.label_41 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_34.addWidget(self.label_41)
        self.label_46 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_34.addWidget(self.label_46)
        self.label_47 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_34.addWidget(self.label_47)
        self.label_53 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_34.addWidget(self.label_53)
        self.label_58 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.horizontalLayout_34.addWidget(self.label_58)
        self.verticalLayout.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(2)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_45 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setMinimumSize(QtCore.QSize(53, 0))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_24.addWidget(self.label_45)
        self.doublePre1Start = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre1Start.sizePolicy().hasHeightForWidth())
        self.doublePre1Start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doublePre1Start.setFont(font)
        self.doublePre1Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre1Start.setWrapping(False)
        self.doublePre1Start.setFrame(True)
        self.doublePre1Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre1Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre1Start.setDecimals(3)
        self.doublePre1Start.setMinimum(-999.999)
        self.doublePre1Start.setMaximum(999.999)
        self.doublePre1Start.setSingleStep(0.0)
        self.doublePre1Start.setProperty("value", -200.0)
        self.doublePre1Start.setObjectName(_fromUtf8("doublePre1Start"))
        self.horizontalLayout_24.addWidget(self.doublePre1Start)
        self.doublePre1Stop = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre1Stop.sizePolicy().hasHeightForWidth())
        self.doublePre1Stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doublePre1Stop.setFont(font)
        self.doublePre1Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre1Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre1Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre1Stop.setDecimals(3)
        self.doublePre1Stop.setMinimum(-999.999)
        self.doublePre1Stop.setMaximum(999.999)
        self.doublePre1Stop.setSingleStep(0.0)
        self.doublePre1Stop.setProperty("value", -50.0)
        self.doublePre1Stop.setObjectName(_fromUtf8("doublePre1Stop"))
        self.horizontalLayout_24.addWidget(self.doublePre1Stop)
        self.doublePre1Step = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre1Step.sizePolicy().hasHeightForWidth())
        self.doublePre1Step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doublePre1Step.setFont(font)
        self.doublePre1Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre1Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre1Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre1Step.setDecimals(3)
        self.doublePre1Step.setMinimum(0.01)
        self.doublePre1Step.setMaximum(999.999)
        self.doublePre1Step.setSingleStep(0.0)
        self.doublePre1Step.setProperty("value", 5.0)
        self.doublePre1Step.setObjectName(_fromUtf8("doublePre1Step"))
        self.horizontalLayout_24.addWidget(self.doublePre1Step)
        self.doublePre1Time = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre1Time.sizePolicy().hasHeightForWidth())
        self.doublePre1Time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doublePre1Time.setFont(font)
        self.doublePre1Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre1Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doublePre1Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre1Time.setDecimals(2)
        self.doublePre1Time.setMinimum(0.01)
        self.doublePre1Time.setMaximum(500.0)
        self.doublePre1Time.setSingleStep(0.0)
        self.doublePre1Time.setProperty("value", 1.0)
        self.doublePre1Time.setObjectName(_fromUtf8("doublePre1Time"))
        self.horizontalLayout_24.addWidget(self.doublePre1Time)
        self.labelPre1Units = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPre1Units.sizePolicy().hasHeightForWidth())
        self.labelPre1Units.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPre1Units.setFont(font)
        self.labelPre1Units.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPre1Units.setObjectName(_fromUtf8("labelPre1Units"))
        self.horizontalLayout_24.addWidget(self.labelPre1Units)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setSpacing(2)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_49 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMinimumSize(QtCore.QSize(53, 0))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_33.addWidget(self.label_49)
        self.doublePre2Start = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre2Start.sizePolicy().hasHeightForWidth())
        self.doublePre2Start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doublePre2Start.setFont(font)
        self.doublePre2Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre2Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre2Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre2Start.setDecimals(3)
        self.doublePre2Start.setMinimum(-999.999)
        self.doublePre2Start.setMaximum(999.999)
        self.doublePre2Start.setSingleStep(0.0)
        self.doublePre2Start.setProperty("value", -50.0)
        self.doublePre2Start.setObjectName(_fromUtf8("doublePre2Start"))
        self.horizontalLayout_33.addWidget(self.doublePre2Start)
        self.doublePre2Stop = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre2Stop.sizePolicy().hasHeightForWidth())
        self.doublePre2Stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doublePre2Stop.setFont(font)
        self.doublePre2Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre2Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre2Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre2Stop.setDecimals(3)
        self.doublePre2Stop.setMinimum(-999.999)
        self.doublePre2Stop.setMaximum(999.999)
        self.doublePre2Stop.setSingleStep(0.0)
        self.doublePre2Stop.setProperty("value", -10.0)
        self.doublePre2Stop.setObjectName(_fromUtf8("doublePre2Stop"))
        self.horizontalLayout_33.addWidget(self.doublePre2Stop)
        self.doublePre2Step = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre2Step.sizePolicy().hasHeightForWidth())
        self.doublePre2Step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doublePre2Step.setFont(font)
        self.doublePre2Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre2Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre2Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre2Step.setDecimals(3)
        self.doublePre2Step.setMinimum(0.01)
        self.doublePre2Step.setMaximum(999.999)
        self.doublePre2Step.setSingleStep(0.0)
        self.doublePre2Step.setProperty("value", 1.0)
        self.doublePre2Step.setObjectName(_fromUtf8("doublePre2Step"))
        self.horizontalLayout_33.addWidget(self.doublePre2Step)
        self.doublePre2Time = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre2Time.sizePolicy().hasHeightForWidth())
        self.doublePre2Time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doublePre2Time.setFont(font)
        self.doublePre2Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre2Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doublePre2Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre2Time.setDecimals(2)
        self.doublePre2Time.setMinimum(0.01)
        self.doublePre2Time.setMaximum(500.0)
        self.doublePre2Time.setSingleStep(0.0)
        self.doublePre2Time.setProperty("value", 1.0)
        self.doublePre2Time.setObjectName(_fromUtf8("doublePre2Time"))
        self.horizontalLayout_33.addWidget(self.doublePre2Time)
        self.labelPre2Units = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPre2Units.sizePolicy().hasHeightForWidth())
        self.labelPre2Units.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPre2Units.setFont(font)
        self.labelPre2Units.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPre2Units.setObjectName(_fromUtf8("labelPre2Units"))
        self.horizontalLayout_33.addWidget(self.labelPre2Units)
        self.verticalLayout.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(2)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_51 = QtGui.QLabel(self.groupBox)
        self.label_51.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setMinimumSize(QtCore.QSize(53, 0))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_31.addWidget(self.label_51)
        self.doubleXANESStart = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXANESStart.sizePolicy().hasHeightForWidth())
        self.doubleXANESStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXANESStart.setFont(font)
        self.doubleXANESStart.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXANESStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXANESStart.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXANESStart.setDecimals(3)
        self.doubleXANESStart.setMinimum(-999.999)
        self.doubleXANESStart.setMaximum(999.999)
        self.doubleXANESStart.setSingleStep(0.0)
        self.doubleXANESStart.setProperty("value", -10.0)
        self.doubleXANESStart.setObjectName(_fromUtf8("doubleXANESStart"))
        self.horizontalLayout_31.addWidget(self.doubleXANESStart)
        self.doubleXANESStop = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXANESStop.sizePolicy().hasHeightForWidth())
        self.doubleXANESStop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXANESStop.setFont(font)
        self.doubleXANESStop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXANESStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXANESStop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXANESStop.setDecimals(3)
        self.doubleXANESStop.setMinimum(-999.999)
        self.doubleXANESStop.setMaximum(999.999)
        self.doubleXANESStop.setSingleStep(0.0)
        self.doubleXANESStop.setProperty("value", 40.0)
        self.doubleXANESStop.setObjectName(_fromUtf8("doubleXANESStop"))
        self.horizontalLayout_31.addWidget(self.doubleXANESStop)
        self.doubleXANESStep = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXANESStep.sizePolicy().hasHeightForWidth())
        self.doubleXANESStep.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXANESStep.setFont(font)
        self.doubleXANESStep.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXANESStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXANESStep.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXANESStep.setDecimals(3)
        self.doubleXANESStep.setMinimum(0.01)
        self.doubleXANESStep.setMaximum(999.999)
        self.doubleXANESStep.setSingleStep(0.0)
        self.doubleXANESStep.setProperty("value", 0.4)
        self.doubleXANESStep.setObjectName(_fromUtf8("doubleXANESStep"))
        self.horizontalLayout_31.addWidget(self.doubleXANESStep)
        self.doubleXANESTime = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXANESTime.sizePolicy().hasHeightForWidth())
        self.doubleXANESTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXANESTime.setFont(font)
        self.doubleXANESTime.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXANESTime.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleXANESTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXANESTime.setDecimals(2)
        self.doubleXANESTime.setMinimum(0.01)
        self.doubleXANESTime.setMaximum(500.0)
        self.doubleXANESTime.setSingleStep(0.0)
        self.doubleXANESTime.setProperty("value", 1.0)
        self.doubleXANESTime.setObjectName(_fromUtf8("doubleXANESTime"))
        self.horizontalLayout_31.addWidget(self.doubleXANESTime)
        self.labelXANESUnits = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelXANESUnits.sizePolicy().hasHeightForWidth())
        self.labelXANESUnits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelXANESUnits.setFont(font)
        self.labelXANESUnits.setStyleSheet(_fromUtf8(""))
        self.labelXANESUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelXANESUnits.setObjectName(_fromUtf8("labelXANESUnits"))
        self.horizontalLayout_31.addWidget(self.labelXANESUnits)
        self.verticalLayout.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setSpacing(2)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_59 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setMinimumSize(QtCore.QSize(53, 0))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.horizontalLayout_35.addWidget(self.label_59)
        self.doubleXAFS1Start = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS1Start.sizePolicy().hasHeightForWidth())
        self.doubleXAFS1Start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS1Start.setFont(font)
        self.doubleXAFS1Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS1Start.setWhatsThis(_fromUtf8(""))
        self.doubleXAFS1Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS1Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS1Start.setDecimals(3)
        self.doubleXAFS1Start.setMinimum(-999.999)
        self.doubleXAFS1Start.setMaximum(999.999)
        self.doubleXAFS1Start.setSingleStep(0.0)
        self.doubleXAFS1Start.setProperty("value", 40.0)
        self.doubleXAFS1Start.setObjectName(_fromUtf8("doubleXAFS1Start"))
        self.horizontalLayout_35.addWidget(self.doubleXAFS1Start)
        self.doubleXAFS1Stop = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS1Stop.sizePolicy().hasHeightForWidth())
        self.doubleXAFS1Stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS1Stop.setFont(font)
        self.doubleXAFS1Stop.setMouseTracking(False)
        self.doubleXAFS1Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS1Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS1Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS1Stop.setDecimals(3)
        self.doubleXAFS1Stop.setMinimum(1.0)
        self.doubleXAFS1Stop.setMaximum(9999.0)
        self.doubleXAFS1Stop.setSingleStep(0.0)
        self.doubleXAFS1Stop.setProperty("value", 549.0)
        self.doubleXAFS1Stop.setObjectName(_fromUtf8("doubleXAFS1Stop"))
        self.horizontalLayout_35.addWidget(self.doubleXAFS1Stop)
        self.doubleXAFS1Step = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS1Step.sizePolicy().hasHeightForWidth())
        self.doubleXAFS1Step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS1Step.setFont(font)
        self.doubleXAFS1Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS1Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS1Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS1Step.setDecimals(3)
        self.doubleXAFS1Step.setMinimum(0.01)
        self.doubleXAFS1Step.setMaximum(999.999)
        self.doubleXAFS1Step.setSingleStep(0.0)
        self.doubleXAFS1Step.setProperty("value", 0.03)
        self.doubleXAFS1Step.setObjectName(_fromUtf8("doubleXAFS1Step"))
        self.horizontalLayout_35.addWidget(self.doubleXAFS1Step)
        self.doubleXAFS1Time = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS1Time.sizePolicy().hasHeightForWidth())
        self.doubleXAFS1Time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS1Time.setFont(font)
        self.doubleXAFS1Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS1Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleXAFS1Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS1Time.setDecimals(2)
        self.doubleXAFS1Time.setMinimum(0.01)
        self.doubleXAFS1Time.setMaximum(500.0)
        self.doubleXAFS1Time.setSingleStep(0.0)
        self.doubleXAFS1Time.setProperty("value", 1.0)
        self.doubleXAFS1Time.setObjectName(_fromUtf8("doubleXAFS1Time"))
        self.horizontalLayout_35.addWidget(self.doubleXAFS1Time)
        self.XAFS1Units = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XAFS1Units.sizePolicy().hasHeightForWidth())
        self.XAFS1Units.setSizePolicy(sizePolicy)
        self.XAFS1Units.setMinimumSize(QtCore.QSize(66, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.XAFS1Units.setFont(font)
        self.XAFS1Units.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XAFS1Units.setMaxVisibleItems(2)
        self.XAFS1Units.setMaxCount(2)
        self.XAFS1Units.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.XAFS1Units.setObjectName(_fromUtf8("XAFS1Units"))
        self.XAFS1Units.addItem(_fromUtf8(""))
        self.XAFS1Units.addItem(_fromUtf8(""))
        self.horizontalLayout_35.addWidget(self.XAFS1Units)
        self.verticalLayout.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(2)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_56 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setMinimumSize(QtCore.QSize(53, 0))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.horizontalLayout_30.addWidget(self.label_56)
        self.doubleXAFS2Start = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS2Start.sizePolicy().hasHeightForWidth())
        self.doubleXAFS2Start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS2Start.setFont(font)
        self.doubleXAFS2Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS2Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS2Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS2Start.setDecimals(3)
        self.doubleXAFS2Start.setMinimum(1.0)
        self.doubleXAFS2Start.setMaximum(9999.0)
        self.doubleXAFS2Start.setSingleStep(0.0)
        self.doubleXAFS2Start.setProperty("value", 549.0)
        self.doubleXAFS2Start.setObjectName(_fromUtf8("doubleXAFS2Start"))
        self.horizontalLayout_30.addWidget(self.doubleXAFS2Start)
        self.doubleXAFS2Stop = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS2Stop.sizePolicy().hasHeightForWidth())
        self.doubleXAFS2Stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS2Stop.setFont(font)
        self.doubleXAFS2Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS2Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS2Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS2Stop.setDecimals(3)
        self.doubleXAFS2Stop.setMinimum(1.0)
        self.doubleXAFS2Stop.setMaximum(9999.0)
        self.doubleXAFS2Stop.setSingleStep(0.0)
        self.doubleXAFS2Stop.setProperty("value", 976.0)
        self.doubleXAFS2Stop.setObjectName(_fromUtf8("doubleXAFS2Stop"))
        self.horizontalLayout_30.addWidget(self.doubleXAFS2Stop)
        self.doubleXAFS2Step = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS2Step.sizePolicy().hasHeightForWidth())
        self.doubleXAFS2Step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS2Step.setFont(font)
        self.doubleXAFS2Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS2Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS2Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS2Step.setDecimals(3)
        self.doubleXAFS2Step.setMinimum(0.01)
        self.doubleXAFS2Step.setMaximum(999.999)
        self.doubleXAFS2Step.setSingleStep(0.0)
        self.doubleXAFS2Step.setProperty("value", 0.05)
        self.doubleXAFS2Step.setObjectName(_fromUtf8("doubleXAFS2Step"))
        self.horizontalLayout_30.addWidget(self.doubleXAFS2Step)
        self.doubleXAFS2Time = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS2Time.sizePolicy().hasHeightForWidth())
        self.doubleXAFS2Time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS2Time.setFont(font)
        self.doubleXAFS2Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS2Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleXAFS2Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS2Time.setDecimals(2)
        self.doubleXAFS2Time.setMinimum(0.01)
        self.doubleXAFS2Time.setMaximum(500.0)
        self.doubleXAFS2Time.setSingleStep(0.0)
        self.doubleXAFS2Time.setProperty("value", 1.0)
        self.doubleXAFS2Time.setObjectName(_fromUtf8("doubleXAFS2Time"))
        self.horizontalLayout_30.addWidget(self.doubleXAFS2Time)
        self.XAFS2Units = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XAFS2Units.sizePolicy().hasHeightForWidth())
        self.XAFS2Units.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.XAFS2Units.setFont(font)
        self.XAFS2Units.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XAFS2Units.setMaxVisibleItems(2)
        self.XAFS2Units.setMaxCount(2)
        self.XAFS2Units.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.XAFS2Units.setFrame(True)
        self.XAFS2Units.setObjectName(_fromUtf8("XAFS2Units"))
        self.XAFS2Units.addItem(_fromUtf8(""))
        self.XAFS2Units.addItem(_fromUtf8(""))
        self.horizontalLayout_30.addWidget(self.XAFS2Units)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setSpacing(2)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_57 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setMinimumSize(QtCore.QSize(53, 0))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalLayout_32.addWidget(self.label_57)
        self.doubleXAFS3Start = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS3Start.sizePolicy().hasHeightForWidth())
        self.doubleXAFS3Start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS3Start.setFont(font)
        self.doubleXAFS3Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS3Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS3Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS3Start.setDecimals(3)
        self.doubleXAFS3Start.setMinimum(1.0)
        self.doubleXAFS3Start.setMaximum(9999.0)
        self.doubleXAFS3Start.setSingleStep(0.0)
        self.doubleXAFS3Start.setProperty("value", 976.0)
        self.doubleXAFS3Start.setObjectName(_fromUtf8("doubleXAFS3Start"))
        self.horizontalLayout_32.addWidget(self.doubleXAFS3Start)
        self.doubleXAFS3Stop = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS3Stop.sizePolicy().hasHeightForWidth())
        self.doubleXAFS3Stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS3Stop.setFont(font)
        self.doubleXAFS3Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS3Stop.setStatusTip(_fromUtf8(""))
        self.doubleXAFS3Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS3Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS3Stop.setDecimals(3)
        self.doubleXAFS3Stop.setMinimum(1.0)
        self.doubleXAFS3Stop.setMaximum(9999.0)
        self.doubleXAFS3Stop.setSingleStep(0.0)
        self.doubleXAFS3Stop.setProperty("value", 1524.0)
        self.doubleXAFS3Stop.setObjectName(_fromUtf8("doubleXAFS3Stop"))
        self.horizontalLayout_32.addWidget(self.doubleXAFS3Stop)
        self.doubleXAFS3Step = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS3Step.sizePolicy().hasHeightForWidth())
        self.doubleXAFS3Step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS3Step.setFont(font)
        self.doubleXAFS3Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS3Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS3Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS3Step.setDecimals(3)
        self.doubleXAFS3Step.setMinimum(0.01)
        self.doubleXAFS3Step.setMaximum(999.999)
        self.doubleXAFS3Step.setSingleStep(0.0)
        self.doubleXAFS3Step.setProperty("value", 0.07)
        self.doubleXAFS3Step.setObjectName(_fromUtf8("doubleXAFS3Step"))
        self.horizontalLayout_32.addWidget(self.doubleXAFS3Step)
        self.doubleXAFS3Time = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleXAFS3Time.sizePolicy().hasHeightForWidth())
        self.doubleXAFS3Time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleXAFS3Time.setFont(font)
        self.doubleXAFS3Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS3Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleXAFS3Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS3Time.setDecimals(2)
        self.doubleXAFS3Time.setMinimum(0.01)
        self.doubleXAFS3Time.setMaximum(500.0)
        self.doubleXAFS3Time.setSingleStep(0.0)
        self.doubleXAFS3Time.setProperty("value", 1.0)
        self.doubleXAFS3Time.setObjectName(_fromUtf8("doubleXAFS3Time"))
        self.horizontalLayout_32.addWidget(self.doubleXAFS3Time)
        self.XAFS3Units = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XAFS3Units.sizePolicy().hasHeightForWidth())
        self.XAFS3Units.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.XAFS3Units.setFont(font)
        self.XAFS3Units.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XAFS3Units.setMaxVisibleItems(2)
        self.XAFS3Units.setMaxCount(2)
        self.XAFS3Units.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.XAFS3Units.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.XAFS3Units.setObjectName(_fromUtf8("XAFS3Units"))
        self.XAFS3Units.addItem(_fromUtf8(""))
        self.XAFS3Units.addItem(_fromUtf8(""))
        self.horizontalLayout_32.addWidget(self.XAFS3Units)
        self.verticalLayout.addLayout(self.horizontalLayout_32)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(roiWidget)
        self.progressBar.setGeometry(QtCore.QRect(470, 210, 331, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.widget = QtGui.QWidget(roiWidget)
        self.widget.setGeometry(QtCore.QRect(470, 10, 331, 41))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plotHistory = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotHistory.sizePolicy().hasHeightForWidth())
        self.plotHistory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plotHistory.setFont(font)
        self.plotHistory.setObjectName(_fromUtf8("plotHistory"))
        self.horizontalLayout.addWidget(self.plotHistory)
        self.history = QtGui.QSpinBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history.sizePolicy().hasHeightForWidth())
        self.history.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.history.setFont(font)
        self.history.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.history.setFrame(True)
        self.history.setAlignment(QtCore.Qt.AlignCenter)
        self.history.setMinimum(1)
        self.history.setMaximum(10)
        self.history.setObjectName(_fromUtf8("history"))
        self.horizontalLayout.addWidget(self.history)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.showItems = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showItems.sizePolicy().hasHeightForWidth())
        self.showItems.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.showItems.setFont(font)
        self.showItems.setFocusPolicy(QtCore.Qt.NoFocus)
        self.showItems.setObjectName(_fromUtf8("showItems"))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.showItems)
        self.widget1 = QtGui.QWidget(roiWidget)
        self.widget1.setGeometry(QtCore.QRect(470, 60, 331, 61))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_12 = QtGui.QLabel(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.selectRegion = QtGui.QComboBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectRegion.sizePolicy().hasHeightForWidth())
        self.selectRegion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectRegion.setFont(font)
        self.selectRegion.setFocusPolicy(QtCore.Qt.NoFocus)
        self.selectRegion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectRegion.setEditable(False)
        self.selectRegion.setObjectName(_fromUtf8("selectRegion"))
        self.selectRegion.addItem(_fromUtf8(""))
        self.selectRegion.addItem(_fromUtf8(""))
        self.selectRegion.addItem(_fromUtf8(""))
        self.selectRegion.addItem(_fromUtf8(""))
        self.selectRegion.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.selectRegion)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.NOS = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NOS.setFont(font)
        self.NOS.setLineWidth(2)
        self.NOS.setAlignment(QtCore.Qt.AlignCenter)
        self.NOS.setIndent(-1)
        self.NOS.setObjectName(_fromUtf8("NOS"))
        self.verticalLayout_8.addWidget(self.NOS)
        self.numberOfscans = QtGui.QSpinBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfscans.sizePolicy().hasHeightForWidth())
        self.numberOfscans.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.numberOfscans.setFont(font)
        self.numberOfscans.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.numberOfscans.setFrame(True)
        self.numberOfscans.setAlignment(QtCore.Qt.AlignCenter)
        self.numberOfscans.setMinimum(1)
        self.numberOfscans.setMaximum(100)
        self.numberOfscans.setObjectName(_fromUtf8("numberOfscans"))
        self.verticalLayout_8.addWidget(self.numberOfscans)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.LabelElement = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LabelElement.setFont(font)
        self.LabelElement.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelElement.setObjectName(_fromUtf8("LabelElement"))
        self.verticalLayout_3.addWidget(self.LabelElement)
        self.elements = QtGui.QComboBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elements.sizePolicy().hasHeightForWidth())
        self.elements.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.elements.setFont(font)
        self.elements.setFocusPolicy(QtCore.Qt.NoFocus)
        self.elements.setMaxVisibleItems(200)
        self.elements.setObjectName(_fromUtf8("elements"))
        self.verticalLayout_3.addWidget(self.elements)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.LabelElement_2 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LabelElement_2.setFont(font)
        self.LabelElement_2.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.LabelElement_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelElement_2.setObjectName(_fromUtf8("LabelElement_2"))
        self.verticalLayout_2.addWidget(self.LabelElement_2)
        self.doubleE0 = QtGui.QDoubleSpinBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleE0.sizePolicy().hasHeightForWidth())
        self.doubleE0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.doubleE0.setFont(font)
        self.doubleE0.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleE0.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.doubleE0.setWrapping(False)
        self.doubleE0.setFrame(True)
        self.doubleE0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleE0.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleE0.setDecimals(1)
        self.doubleE0.setMinimum(4000.0)
        self.doubleE0.setMaximum(99999.0)
        self.doubleE0.setSingleStep(0.0)
        self.doubleE0.setProperty("value", 7112.0)
        self.doubleE0.setObjectName(_fromUtf8("doubleE0"))
        self.verticalLayout_2.addWidget(self.doubleE0)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.widget2 = QtGui.QWidget(roiWidget)
        self.widget2.setGeometry(QtCore.QRect(470, 130, 331, 71))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnStartScan = QtGui.QPushButton(self.widget2)
        self.btnStartScan.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartScan.sizePolicy().hasHeightForWidth())
        self.btnStartScan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnStartScan.setFont(font)
        self.btnStartScan.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.btnStartScan.setObjectName(_fromUtf8("btnStartScan"))
        self.horizontalLayout_4.addWidget(self.btnStartScan)
        self.btnStopScan = QtGui.QPushButton(self.widget2)
        self.btnStopScan.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStopScan.sizePolicy().hasHeightForWidth())
        self.btnStopScan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnStopScan.setFont(font)
        self.btnStopScan.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
""))
        self.btnStopScan.setObjectName(_fromUtf8("btnStopScan"))
        self.horizontalLayout_4.addWidget(self.btnStopScan)
        self.btnE0 = QtGui.QPushButton(self.widget2)
        self.btnE0.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnE0.sizePolicy().hasHeightForWidth())
        self.btnE0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnE0.setFont(font)
        self.btnE0.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
""))
        self.btnE0.setObjectName(_fromUtf8("btnE0"))
        self.horizontalLayout_4.addWidget(self.btnE0)
        self.groupBox.raise_()
        self.LabelElement_2.raise_()
        self.doubleE0.raise_()
        self.elements.raise_()
        self.btnStopScan.raise_()
        self.btnStartScan.raise_()
        self.btnE0.raise_()
        self.showItems.raise_()
        self.progressBar.raise_()

        self.retranslateUi(roiWidget)
        self.XAFS1Units.setCurrentIndex(1)
        self.XAFS2Units.setCurrentIndex(1)
        self.XAFS3Units.setCurrentIndex(1)
        self.selectRegion.setCurrentIndex(3)
        self.elements.setCurrentIndex(-1)
        QtCore.QObject.connect(self.doublePre1Stop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doublePre2Start.setValue)
        QtCore.QObject.connect(self.doublePre2Stop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXANESStart.setValue)
        QtCore.QObject.connect(self.doubleXANESStop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS1Start.setValue)
        QtCore.QObject.connect(self.doubleXAFS1Stop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS2Start.setValue)
        QtCore.QObject.connect(self.doubleXAFS2Stop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS3Start.setValue)
        QtCore.QObject.connect(self.doublePre2Start, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doublePre1Stop.setValue)
        QtCore.QObject.connect(self.doubleXANESStart, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doublePre2Stop.setValue)
        QtCore.QObject.connect(self.doubleXAFS1Start, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXANESStop.setValue)
        QtCore.QObject.connect(self.doubleXAFS2Start, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS1Stop.setValue)
        QtCore.QObject.connect(self.doubleXAFS3Start, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS2Stop.setValue)
        QtCore.QMetaObject.connectSlotsByName(roiWidget)

    def retranslateUi(self, roiWidget):
        roiWidget.setWindowTitle(_translate("roiWidget", "Form", None))
        self.groupBox.setTitle(_translate("roiWidget", "Set ROI", None))
        self.label.setText(_translate("roiWidget", "Region", None))
        self.label_41.setText(_translate("roiWidget", "Start", None))
        self.label_46.setText(_translate("roiWidget", "Stop", None))
        self.label_47.setText(_translate("roiWidget", "Step", None))
        self.label_53.setText(_translate("roiWidget", "Time(s)", None))
        self.label_58.setText(_translate("roiWidget", "Units", None))
        self.label_45.setText(_translate("roiWidget", "Pre-Edge1", None))
        self.labelPre1Units.setText(_translate("roiWidget", "eV", None))
        self.label_49.setText(_translate("roiWidget", "Pre-Edge2", None))
        self.labelPre2Units.setText(_translate("roiWidget", "eV", None))
        self.label_51.setText(_translate("roiWidget", "XANES", None))
        self.doubleXANESStop.setToolTip(_translate("roiWidget", "<html><head/><body><p>3.24k--> 40eV</p></body></html>", None))
        self.labelXANESUnits.setText(_translate("roiWidget", "eV", None))
        self.label_59.setText(_translate("roiWidget", "XAFS1", None))
        self.doubleXAFS1Start.setToolTip(_translate("roiWidget", "<html><head/><body><p>3.24k--> 40eV</p></body></html>", None))
        self.doubleXAFS1Stop.setToolTip(_translate("roiWidget", "<html><head/><body><p>12k --> 549eV</p></body></html>", None))
        self.doubleXAFS1Step.setToolTip(_translate("roiWidget", "<html><head/><body><p>Default 0.03</p></body></html>", None))
        self.XAFS1Units.setItemText(0, _translate("roiWidget", "eV", None))
        self.XAFS1Units.setItemText(1, _translate("roiWidget", "k", None))
        self.label_56.setText(_translate("roiWidget", "XAFS2", None))
        self.doubleXAFS2Start.setToolTip(_translate("roiWidget", "<html><head/><body><p>12k --> 549eV</p></body></html>", None))
        self.doubleXAFS2Stop.setToolTip(_translate("roiWidget", "<html><head/><body><p>16k --> 976eV</p></body></html>", None))
        self.doubleXAFS2Step.setToolTip(_translate("roiWidget", "<html><head/><body><p>Default 0.05</p></body></html>", None))
        self.XAFS2Units.setItemText(0, _translate("roiWidget", "eV", None))
        self.XAFS2Units.setItemText(1, _translate("roiWidget", "k", None))
        self.label_57.setText(_translate("roiWidget", "XAFS3", None))
        self.doubleXAFS3Start.setToolTip(_translate("roiWidget", "<html><head/><body><p>16k --> 976eV</p></body></html>", None))
        self.doubleXAFS3Stop.setToolTip(_translate("roiWidget", "<html><head/><body><p>\'20K --> 1524eV\'</p></body></html>", None))
        self.doubleXAFS3Stop.setWhatsThis(_translate("roiWidget", "<html><head/><body><p>\'20k --> 1524eV\'</p></body></html>", None))
        self.doubleXAFS3Step.setToolTip(_translate("roiWidget", "<html><head/><body><p>Default 0.07</p></body></html>", None))
        self.XAFS3Units.setItemText(0, _translate("roiWidget", "eV", None))
        self.XAFS3Units.setItemText(1, _translate("roiWidget", "k", None))
        self.plotHistory.setText(_translate("roiWidget", "# History", None))
        self.showItems.setItemText(0, _translate("roiWidget", "Transmittance", None))
        self.showItems.setItemText(1, _translate("roiWidget", "Floulescence", None))
        self.showItems.setItemText(2, _translate("roiWidget", "Io only", None))
        self.showItems.setItemText(3, _translate("roiWidget", "It only", None))
        self.showItems.setItemText(4, _translate("roiWidget", "If only", None))
        self.showItems.setItemText(5, _translate("roiWidget", "Ir only", None))
        self.label_12.setText(_translate("roiWidget", "# region", None))
        self.selectRegion.setItemText(0, _translate("roiWidget", "Pre2", None))
        self.selectRegion.setItemText(1, _translate("roiWidget", "XANES", None))
        self.selectRegion.setItemText(2, _translate("roiWidget", "XAFS1", None))
        self.selectRegion.setItemText(3, _translate("roiWidget", "XAFS2", None))
        self.selectRegion.setItemText(4, _translate("roiWidget", "XAFS3", None))
        self.NOS.setText(_translate("roiWidget", "# scans", None))
        self.LabelElement.setText(_translate("roiWidget", "elements", None))
        self.LabelElement_2.setText(_translate("roiWidget", "E0", None))
        self.btnStartScan.setText(_translate("roiWidget", "SCAN Start", None))
        self.btnStopScan.setText(_translate("roiWidget", "SCAN Stop", None))
        self.btnE0.setText(_translate("roiWidget", "MOVE to E0", None))

