# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_monitorWidget(object):
    def setupUi(self, monitorWidget):
        monitorWidget.setObjectName(_fromUtf8("monitorWidget"))
        monitorWidget.resize(163, 239)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        monitorWidget.setFont(font)
        self.groupBox = QtGui.QGroupBox(monitorWidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 161, 231))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.beamCurrent = QtGui.QLCDNumber(self.groupBox)
        self.beamCurrent.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beamCurrent.sizePolicy().hasHeightForWidth())
        self.beamCurrent.setSizePolicy(sizePolicy)
        self.beamCurrent.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.beamCurrent.setFrameShape(QtGui.QFrame.NoFrame)
        self.beamCurrent.setSmallDecimalPoint(False)
        self.beamCurrent.setDigitCount(10)
        self.beamCurrent.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.beamCurrent.setObjectName(_fromUtf8("beamCurrent"))
        self.horizontalLayout_3.addWidget(self.beamCurrent)
        self.label_6 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.M1Pos = QtGui.QLCDNumber(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M1Pos.sizePolicy().hasHeightForWidth())
        self.M1Pos.setSizePolicy(sizePolicy)
        self.M1Pos.setFrameShape(QtGui.QFrame.NoFrame)
        self.M1Pos.setSmallDecimalPoint(False)
        self.M1Pos.setDigitCount(10)
        self.M1Pos.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.M1Pos.setObjectName(_fromUtf8("M1Pos"))
        self.horizontalLayout_4.addWidget(self.M1Pos)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.M2Pos = QtGui.QLCDNumber(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M2Pos.sizePolicy().hasHeightForWidth())
        self.M2Pos.setSizePolicy(sizePolicy)
        self.M2Pos.setFrameShape(QtGui.QFrame.NoFrame)
        self.M2Pos.setSmallDecimalPoint(False)
        self.M2Pos.setDigitCount(10)
        self.M2Pos.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.M2Pos.setObjectName(_fromUtf8("M2Pos"))
        self.horizontalLayout_5.addWidget(self.M2Pos)
        self.label_12 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.IoCnt = QtGui.QLCDNumber(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IoCnt.sizePolicy().hasHeightForWidth())
        self.IoCnt.setSizePolicy(sizePolicy)
        self.IoCnt.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.IoCnt.setFrameShape(QtGui.QFrame.NoFrame)
        self.IoCnt.setSmallDecimalPoint(False)
        self.IoCnt.setDigitCount(10)
        self.IoCnt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.IoCnt.setObjectName(_fromUtf8("IoCnt"))
        self.horizontalLayout_6.addWidget(self.IoCnt)
        self.label_7 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ItCnt = QtGui.QLCDNumber(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ItCnt.sizePolicy().hasHeightForWidth())
        self.ItCnt.setSizePolicy(sizePolicy)
        self.ItCnt.setFrameShape(QtGui.QFrame.NoFrame)
        self.ItCnt.setSmallDecimalPoint(False)
        self.ItCnt.setDigitCount(10)
        self.ItCnt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.ItCnt.setObjectName(_fromUtf8("ItCnt"))
        self.horizontalLayout_7.addWidget(self.ItCnt)
        self.label_8 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.IfCnt = QtGui.QLCDNumber(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IfCnt.sizePolicy().hasHeightForWidth())
        self.IfCnt.setSizePolicy(sizePolicy)
        self.IfCnt.setFrameShape(QtGui.QFrame.NoFrame)
        self.IfCnt.setSmallDecimalPoint(False)
        self.IfCnt.setDigitCount(10)
        self.IfCnt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.IfCnt.setObjectName(_fromUtf8("IfCnt"))
        self.horizontalLayout_8.addWidget(self.IfCnt)
        self.label_9 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.IrCnt = QtGui.QLCDNumber(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IrCnt.sizePolicy().hasHeightForWidth())
        self.IrCnt.setSizePolicy(sizePolicy)
        self.IrCnt.setFrameShape(QtGui.QFrame.NoFrame)
        self.IrCnt.setSmallDecimalPoint(False)
        self.IrCnt.setDigitCount(10)
        self.IrCnt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.IrCnt.setObjectName(_fromUtf8("IrCnt"))
        self.horizontalLayout_9.addWidget(self.IrCnt)
        self.label_10 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(monitorWidget)
        QtCore.QMetaObject.connectSlotsByName(monitorWidget)

    def retranslateUi(self, monitorWidget):
        monitorWidget.setWindowTitle(_translate("monitorWidget", "Form", None))
        self.groupBox.setTitle(_translate("monitorWidget", "monitor", None))
        self.label_6.setText(_translate("monitorWidget", "mA", None))
        self.label_13.setText(_translate("monitorWidget", "eV", None))
        self.label_12.setText(_translate("monitorWidget", "mm", None))
        self.label_7.setText(_translate("monitorWidget", "Io", None))
        self.label_8.setText(_translate("monitorWidget", "It", None))
        self.label_9.setText(_translate("monitorWidget", "If", None))
        self.label_10.setText(_translate("monitorWidget", "Ir", None))

